import { useState, useEffect, useMemo } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { GlobalData, CountryData } from './types';
import fetchCountry from './hooks/fetchCountry';
import fetchGlobal from './hooks/fetchGlobal';
import { getGlobalSpecific } from './functions/getGlobalSpecific';
import { getGlobalAmountDiff } from './functions/getGlobalAmountDiff';
import styles from '../styles/Home.module.css';
import SearchBar from './components/SearchBar';
import StatisticCard from './components/StatisticCard';

const Home: NextPage = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [globalData, setGlobalData] = useState<GlobalData>();
  const [globalLoading, setGlobalLoading] = useState(false);
  const [countryData, setCountryData] = useState<CountryData>();
  const [countryLoading, setCountryLoading] = useState(false);

  // fetch global data on initial load
  useEffect(() => {
    setGlobalLoading(true);
    fetchGlobal().then((res) => {
      if (res) {
        setGlobalLoading(false);
        setGlobalData(res);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // fetch country specific data if queried
  useEffect(() => {
    searchTerm.length > 0 && fetchCountry(searchTerm).then((res) => res && setCountryData(res));
  }, [searchTerm]);

  const globalDeaths = useMemo(() => getGlobalSpecific(globalData, 'deaths', 1), [globalData]);
  const globalCases = useMemo(() => getGlobalSpecific(globalData, 'cases', 1), [globalData]);
  const globalRecovered = useMemo(() => getGlobalSpecific(globalData, 'recovered', 1), [globalData]);

  const globalDeaths30 = useMemo(() => getGlobalAmountDiff(getGlobalSpecific(globalData, 'deaths', 31)), [globalData]);
  const globalCases30 = useMemo(() => getGlobalAmountDiff(getGlobalSpecific(globalData, 'cases', 31)), [globalData]);
  const globalRecovered30 = useMemo(
    () => getGlobalAmountDiff(getGlobalSpecific(globalData, 'recovered', 31)),
    [globalData]
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid Tracker</title>
        <meta name="Worldwide covid-19 case tracker" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SearchBar setSearchTerm={setSearchTerm} />
        <div className={styles.grid}>
          <StatisticCard
            loading={globalLoading}
            title="Global Cases"
            data={globalCases ? globalCases[0].amount : 0}
            dataColor="#c84b31"
          />
          <StatisticCard
            loading={globalLoading}
            title="Global Recovered"
            data={globalRecovered ? globalRecovered[0].amount : 0}
            dataColor="#458B00"
          />
          <StatisticCard
            loading={globalLoading}
            title="Global Deaths"
            data={globalDeaths ? globalDeaths[0].amount : 0}
            dataColor="#ff0000"
          />
        </div>
        <div className={styles.grid}>
          <StatisticCard
            loading={globalLoading}
            title="30 Days Cases"
            data={globalDeaths30 ? globalCases30.amount : 0}
            dataColor="#ff0000"
          />
          <StatisticCard
            loading={globalLoading}
            title="30 Days Recovered"
            data={globalDeaths30 ? globalRecovered30.amount : 0}
            dataColor="#ff0000"
          />
          <StatisticCard
            loading={globalLoading}
            title="30 Days Deaths"
            data={globalDeaths30 ? globalDeaths30.amount : 0}
            dataColor="#ff0000"
          />
        </div>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </main>
    </div>
  );
};

export default Home;
